/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: overlaps (https://sketchfab.com/overlaps)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
    const { nodes, materials } = useGLTF("/scene/scene.glb");
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group
                    position={[-0.003, 0.024, -6.331]}
                    rotation={[0.238, -0.545, 0.562]}
                    scale={7}
                >
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.planet002.geometry}
                        material={materials.scene}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.planet003.geometry}
                        material={materials.scene}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/scene/scene.glb");
